apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-chart-deploy-nginx 
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: nginx-index
          configMap:
            name: nginx-index-html-configmap
#      securityContext:
#        runAsUser: {{ .Values.securityContext.runAsUser }}
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
            - name: nginx-index
              mountPath: /usr/share/nginx/html
