apiVersion: v1
kind: Service
metadata:
  name: my-chart-deploy-nginx-svc 
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: nginx
