apiVersion: v1
kind: Pod
metadata:
  name: init-pod
spec:
  containers:
  - name: nginx
    image: nginx:1.19.1
  initContainers:
  - name: delay
    image: busybox
    command: ['sh', '-c', 'sleep 10; echo "Init container 1 job done"']
  - name: delay2
    image: busybox
    command: ['sh', '-c', 'sleep 10; echo "Init container 2 job done"']

