apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: httpd
  name: test-pod2
spec:
  containers:
  - image: httpd
    name: test-pod2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
